### ISSUE TITLE
I was able to edit tools that were not mine (⚠️security issue⚠️)

### ISSUE THREAD

**Issue by marklocklear** [meghanduprey/tool_library#11]
On the edit tool page like https://mduprey.com/toollibrary/public/members/edit_tool.php?id=7 I was able to change the id in the URL and go to another tools page and edit its info.

**Comment by meghanduprey** [comment]
https://github.com/meghanduprey/tool_library/commit/d22165cdc3e993e598c01f4578e5fc188153aa41
