### ISSUE TITLE
Adding a review fails

### ISSUE THREAD

**Issue by marklocklear** [meghanduprey/tool_library#8]
I get the error below when trying to add a review:

![image](https://user-images.githubusercontent.com/505198/75473576-6d621400-5963-11ea-8dbe-145d7c8145ff.png)

**Comment by meghanduprey** [comment]
I think I have this issue fixed, I just left a review and it worked

**Comment by marklocklear** [comment]
@meghanduprey You should include the commit here when you fix an issue.
